[package]
name = "tokio-ddmw"
version = "0.5.2"
authors = ["Jan Danielsson <jan.danielsson@qrnch.com>"]
edition = "2018"
license = "0BSD"
keywords = [ "tokio", "ddmw" ]
repository = "https://github.com/openqrnch/tokio-ddmw"
description = "Library for integrating clients against DDMW."

[dependencies]
blather = { version = "0.3", features = ["bytes"] }
bytes = { version = "0.5" }
futures = { version = "0.3" }
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version= "0.3", features = ["full"] }

